import Head from 'next/head'
import { useEffect, useState } from 'react'
import {  useSelector } from 'react-redux'
import { useRouter } from 'next/router'
import { getUserFromLocalStorage } from '@/utils/localStorage'


export default function Home() {
  const router = useRouter()
   const {user} = useSelector(state => state.user)
  useEffect(() => {
    // let user = getUserFromLocalStorage(); 
    console.log('user in index is:' + user)
    if(user != null) {
      router.push('/test')
    } else {
      router.push('/auth/login')
    }
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div></div>
      </main>
    </>
  )
}
